### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by xypron** [sebcrozet/glpk-rs#1]
The project does not contain any license information, so it is unclear how it can be used.

Please, create a file COPYING or LICENSE in the top level directory. The license has to be compatible with the GNU Public License used by GLPK, cf http://www.gnu.org/licenses/license-list.en.html.

I suggest you use either
    https://github.com/rust-lang/rust/blob/master/LICENSE-MIT
or
    http://www.gnu.org/licenses/gpl-3.0.txt

Best regards

Heinrich Schuchardt

**Comment by sebcrozet** [comment]
I added the MIT license. Though this project is no longer maintained and will probably not compile with the latest rust release. I am willing to give write access to whoever wants to continue the development.
